// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pigresponse.proto

#ifndef PROTOBUF_pigresponse_2eproto__INCLUDED
#define PROTOBUF_pigresponse_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Pig {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_pigresponse_2eproto();
void protobuf_AssignDesc_pigresponse_2eproto();
void protobuf_ShutdownFile_pigresponse_2eproto();

class PigResponse;

// ===================================================================

class PigResponse : public ::google::protobuf::Message {
 public:
  PigResponse();
  virtual ~PigResponse();

  PigResponse(const PigResponse& from);

  inline PigResponse& operator=(const PigResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PigResponse& default_instance();

  void Swap(PigResponse* other);

  // implements Message ----------------------------------------------

  PigResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PigResponse& from);
  void MergeFrom(const PigResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 status = 1;
  inline bool has_status() const;
  inline void clear_status();
  static const int kStatusFieldNumber = 1;
  inline ::google::protobuf::int32 status() const;
  inline void set_status(::google::protobuf::int32 value);

  // required string data = 2;
  inline bool has_data() const;
  inline void clear_data();
  static const int kDataFieldNumber = 2;
  inline const ::std::string& data() const;
  inline void set_data(const ::std::string& value);
  inline void set_data(const char* value);
  inline void set_data(const char* value, size_t size);
  inline ::std::string* mutable_data();
  inline ::std::string* release_data();
  inline void set_allocated_data(::std::string* data);

  // @@protoc_insertion_point(class_scope:Pig.PigResponse)
 private:
  inline void set_has_status();
  inline void clear_has_status();
  inline void set_has_data();
  inline void clear_has_data();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* data_;
  ::google::protobuf::int32 status_;
  friend void  protobuf_AddDesc_pigresponse_2eproto();
  friend void protobuf_AssignDesc_pigresponse_2eproto();
  friend void protobuf_ShutdownFile_pigresponse_2eproto();

  void InitAsDefaultInstance();
  static PigResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// PigResponse

// required int32 status = 1;
inline bool PigResponse::has_status() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PigResponse::set_has_status() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PigResponse::clear_has_status() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PigResponse::clear_status() {
  status_ = 0;
  clear_has_status();
}
inline ::google::protobuf::int32 PigResponse::status() const {
  // @@protoc_insertion_point(field_get:Pig.PigResponse.status)
  return status_;
}
inline void PigResponse::set_status(::google::protobuf::int32 value) {
  set_has_status();
  status_ = value;
  // @@protoc_insertion_point(field_set:Pig.PigResponse.status)
}

// required string data = 2;
inline bool PigResponse::has_data() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PigResponse::set_has_data() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PigResponse::clear_has_data() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PigResponse::clear_data() {
  if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_->clear();
  }
  clear_has_data();
}
inline const ::std::string& PigResponse::data() const {
  // @@protoc_insertion_point(field_get:Pig.PigResponse.data)
  return *data_;
}
inline void PigResponse::set_data(const ::std::string& value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(value);
  // @@protoc_insertion_point(field_set:Pig.PigResponse.data)
}
inline void PigResponse::set_data(const char* value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(value);
  // @@protoc_insertion_point(field_set_char:Pig.PigResponse.data)
}
inline void PigResponse::set_data(const char* value, size_t size) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Pig.PigResponse.data)
}
inline ::std::string* PigResponse::mutable_data() {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:Pig.PigResponse.data)
  return data_;
}
inline ::std::string* PigResponse::release_data() {
  clear_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = data_;
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void PigResponse::set_allocated_data(::std::string* data) {
  if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete data_;
  }
  if (data) {
    set_has_data();
    data_ = data;
  } else {
    clear_has_data();
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:Pig.PigResponse.data)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Pig

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_pigresponse_2eproto__INCLUDED
